### PR TITLE
Visual Studio 2017 Support: Update source.extension.vsixmanifest

### PR DESCRIPTION
**Pull request by josuelopezv**
added support to VS 2017

### CODE REVIEW

**Comment by MikeMazz23** [comment]
Thank you updating this for VS2017! Do we know what is holding up this request?

**Comment by josuelopezv** [comment]
No idea. It's working they should be able to commit this to main branch

**Comment by JulienM28** [comment]
I have an issue. 
I Built the VSIX Extension and installed it to Visual Studio but when creating a nex Chrome extension project I get this error:
Argument can't be null Parameter name: node

**Comment by josuelopezv** [comment]
can you post the full error including the file in confict and stack trace

**Comment by JulienM28** [comment]
I just tried again to send you the trace, but it worked perfectly.
I apologize.

**Pull request merged**
